name: omstudio
favicon: null
layout_spectrum: 0.1330139795318246
typography_spectrum: 0.14448
title: OM Studio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34393c'
    - '#477132'
    - '#7b7874'
    - '#1b1c18'
    - '#75953f'
  brandStrength: 0.6850091458763927
  lightness: 0.5774103777948767
  saturation: 0.851752859307453
  rhythmicContrast: 0.13212123303674161
purpose: []
