name: omstudio
favicon: null
layout_spectrum: 0.1330139795318246
typography_spectrum: 0.2596721677109599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6850091458763927
  lightness: 0.5774103777948767
  saturation: 0.851752859307453
  rhythmicContrast: 0.13212123303674161
purpose: []
